// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {IVerifier} from "./IVerifier.sol";

/// @notice Test double for the Noir/Honk verifier generated by `bb`.
/// @dev Contains NO cryptography, on purpose. Realism comes from the fixtures:
///      tests pass real `proof` / `publicInputs` captured from the dapp, and this
///      contract only drives the outcome.
///
///      `Panagram.claimReward` checks the claimer binding and the nullifier
///      *before* calling `verify`, so those paths never reach this contract.
///
///      NOT covered here: proof soundness and public-input ordering. A mock accepts
///      any array, so a wrong `PUBLIC_INPUT_*_INDEX` passes every unit test. That
///      needs an integration test against the real verifier.
contract MockVerifier is IVerifier {
    /// @notice The three outcomes the real generated verifier can produce.
    /// @dev `Panagram` only branches on Accept/Reject. Revert exists because the
    ///      real verifier reverts on malformed input (`ProofLengthWrongWithLogN`,
    ///      public-inputs length mismatch) and on some proof failures — in which
    ///      case the tx dies with the verifier's error and `Panagram__InvalidProof`
    ///      is never reached. Tests should pin that difference.
    enum Behavior {
        Accept, // returns true  -> Panagram mints
        Reject, // returns false -> Panagram__InvalidProof
        Revert // reverts       -> Panagram__InvalidProof is NOT reached
    }

    error MockVerifier__VerificationFailed();

    Behavior private s_behavior = Behavior.Accept;

    /// @notice Sets the outcome of subsequent `verify` calls. Defaults to `Accept`.
    /// @dev Must be configured beforehand: `verify` is `view`, so it cannot record
    ///      or mutate anything itself.
    function setBehavior(Behavior _behavior) external {
        s_behavior = _behavior;
    }

    /// @inheritdoc IVerifier
    /// @dev `view` to match IVerifier — `Panagram` reaches this via STATICCALL, so
    ///      this function must not write storage.
    function verify(
        bytes calldata,
        bytes32[] calldata
    ) external view returns (bool) {
        if (s_behavior == Behavior.Revert) {
            revert MockVerifier__VerificationFailed();
        }
        return s_behavior == Behavior.Accept;
    }
}
